import FWCore.ParameterSet.Config as cms

generator = cms.EDFilter("HydjetGeneratorFilter",
    aBeamTarget = cms.double(208.0),
    comEnergy = cms.double(2760.0),
    qgpInitialTemperature = cms.double(1.0),
    doCollisionalEnLoss = cms.bool(True),
    qgpNumQuarkFlavor = cms.int32(0),
    qgpProperTimeFormation = cms.double(0.1),
    angularSpectrumSelector = cms.int32(1),
    numQuarkFlavor = cms.int32(0),
    hadronFreezoutTemperature = cms.double(0.125),
    doRadiativeEnLoss = cms.bool(True),
    nMultiplicity = cms.int32(18500),
    embeddingMode = cms.bool(False),
    maxLongitudinalRapidity = cms.double(4.5),
    shadowingSwitch = cms.int32(1),
    maxTransverseRapidity = cms.double(1.15),
    sigmaInelNN = cms.double(64),
    fracSoftMultiplicity = cms.double(1.0),
    allowEmptyEvents = cms.bool(False),
    rotateEventPlane = cms.bool(True),
    cFlag = cms.int32(1),
    bFixed = cms.double(0),
    bMin = cms.double(0),
    hydjetMode = cms.string('kHydroQJets'),
    bMax = cms.double(30),
    PythiaParameters = cms.PSet(
        pythiaUpsilonToMuons = cms.vstring('BRAT(1034) = 0 ', 
            'BRAT(1035) = 1 ', 
            'BRAT(1036) = 0 ', 
            'BRAT(1037) = 0 ', 
            'BRAT(1038) = 0 ', 
            'BRAT(1039) = 0 ', 
            'BRAT(1040) = 0 ', 
            'BRAT(1041) = 0 ', 
            'BRAT(1042) = 0 ', 
            'MDME(1034,1) = 0 ', 
            'MDME(1035,1) = 1 ', 
            'MDME(1036,1) = 0 ', 
            'MDME(1037,1) = 0 ', 
            'MDME(1038,1) = 0 ', 
            'MDME(1039,1) = 0 ', 
            'MDME(1040,1) = 0 ', 
            'MDME(1041,1) = 0 ', 
            'MDME(1042,1) = 0 '),
        decayParameters = cms.vstring('MDCY(310,1)=0'),
        customProcesses = cms.vstring('MSEL=0   ! User processes'),
        ppDefault = cms.vstring('MSEL=1   ! QCD hight pT processes (only jets)', 
            'CKIN(3)=7.5', 
            'MSTP(81)=1'),
        pythiaZtoElectrons = cms.vstring('MDME(174,1)=0', 
            'MDME(175,1)=0', 
            'MDME(176,1)=0', 
            'MDME(177,1)=0', 
            'MDME(178,1)=0', 
            'MDME(179,1)=0', 
            'MDME(182,1)=1', 
            'MDME(183,1)=0', 
            'MDME(184,1)=0', 
            'MDME(185,1)=0', 
            'MDME(186,1)=0', 
            'MDME(187,1)=0'),
        pythiaZjets = cms.vstring('MSUB(15)=1', 
            'MSUB(30)=1'),
        pythiaUESettingsDrum = cms.vstring(
            'MSTP(51)=7                 ! PDF set',                                      
            'MSTP(3)=2                  ! QCD switch for choice of LambdaQCD',           
            'PARP(62)=2.9               ! ISR IR cutoff',                                
            'PARP(64)=0.14              ! ISR renormalization scale prefactor',          
            'PARP(67)=2.65              ! ISR Q2max factor',
            'MSTP(68)=3                 ! ISR phase space choice & ME corrections',      
            'PARP(71)=4.                ! FSR Q2max factor for non-s-channel procs',     
            'PARJ(81)=0.29              ! FSR Lambda_QCD scale',                         
            'PARJ(82)=1.65              ! FSR IR cutoff',                                
            'MSTP(33)=0                 ! "K" switch for K-factor on/off & type',        
            'MSTP(81)=1                 ! UE model',                                     
            'PARP(82)=1.9               ! UE IR cutoff at reference ecm',               
            'PARP(89)=1800.             ! UE IR cutoff reference ecm',                   
            'PARP(90)=0.22              ! UE IR cutoff ecm scaling power',               
            'MSTP(82)=4                 ! UE hadron transverse mass distribution',       
            'PARP(83)=0.83              ! UE mass distribution parameter',               
            'PARP(84)=0.6               ! UE mass distribution parameter',              
            'PARP(85)=0.86              ! UE gg colour correlated fraction',             
            'PARP(86)=0.93              ! UE total gg fraction',                         
            'MSTP(91)=1                 ! BR primordial kT distribution',                
            'PARP(91)=2.1               ! BR primordial kT width <|kT|>',                
            'PARP(93)=5.                ! BR primordial kT UV cutoff',               
            'MSTJ(11)=5                 ! HAD choice of fragmentation function(s)',      
            'PARJ(1)=0.073              ! HAD diquark suppression',                      
            'PARJ(2)=0.2                ! HAD strangeness suppression',                  
            'PARJ(3)=0.94               ! HAD strange diquark suppression',              
            'PARJ(4)=0.032              ! HAD vector diquark suppression',               
            'PARJ(11)=0.31              ! HAD P(vector meson), u and d only',            
            'PARJ(12)=0.4               ! HAD P(vector meson), contains s',              
            'PARJ(13)=0.54              ! HAD P(vector meson), heavy quarks',            
            'PARJ(21)=0.325             ! HAD fragmentation pT',                         
            'PARJ(25)=0.63              ! HAD eta0 suppression',                        
            'PARJ(26)=0.12              ! HAD eta0 suppression',                       
            'PARJ(41)=0.5               ! HAD string parameter a',                       
            'PARJ(42)=0.6               ! HAD string parameter b',                       
            'PARJ(46)=1.                ! HAD Lund(=0)-Bowler(=1) rQ (rc)',              
            'PARJ(47)=0.67              ! HAD Lund(=0)-Bowler(=1) rb'),     
        pythiaZtoMuonsAndElectrons = cms.vstring('MDME(174,1)=0', 
            'MDME(175,1)=0', 
            'MDME(176,1)=0', 
            'MDME(177,1)=0', 
            'MDME(178,1)=0', 
            'MDME(179,1)=0', 
            'MDME(182,1)=1', 
            'MDME(183,1)=0', 
            'MDME(184,1)=1', 
            'MDME(185,1)=0', 
            'MDME(186,1)=0', 
            'MDME(187,1)=0'),
        pythiaPromptPhotons = cms.vstring('MSUB(14)=1', 
            'MSUB(18)=1', 
            'MSUB(29)=1', 
            'MSUB(114)=1', 
            'MSUB(115)=1'),
        pythiaCharmoniumNRQCD = cms.vstring('MSUB(421) = 1', 
            'MSUB(422) = 1', 
            'MSUB(423) = 1', 
            'MSUB(424) = 1', 
            'MSUB(425) = 1', 
            'MSUB(426) = 1', 
            'MSUB(427) = 1', 
            'MSUB(428) = 1', 
            'MSUB(429) = 1', 
            'MSUB(430) = 1', 
            'MSUB(431) = 1', 
            'MSUB(432) = 1', 
            'MSUB(433) = 1', 
            'MSUB(434) = 1', 
            'MSUB(435) = 1', 
            'MSUB(436) = 1', 
            'MSUB(437) = 1', 
            'MSUB(438) = 1', 
            'MSUB(439) = 1'),
        pythiaMuonCandidates = cms.vstring('CKIN(3)=20', 
            'MSTJ(22)=2', 
            'PARJ(71)=40.'),
        pythiaQuarkoniaSettings = cms.vstring('PARP(141)=1.16', 
            'PARP(142)=0.0119', 
            'PARP(143)=0.01', 
            'PARP(144)=0.01', 
            'PARP(145)=0.05', 
            'PARP(146)=9.28', 
            'PARP(147)=0.15', 
            'PARP(148)=0.02', 
            'PARP(149)=0.02', 
            'PARP(150)=0.085', 
            'PARJ(13)=0.60', 
            'PARJ(14)=0.162', 
            'PARJ(15)=0.018', 
            'PARJ(16)=0.054', 
            'MSTP(145)=0', 
            'MSTP(146)=0', 
            'MSTP(147)=0', 
            'MSTP(148)=1', 
            'MSTP(149)=1', 
            'BRAT(861)=0.202', 
            'BRAT(862)=0.798', 
            'BRAT(1501)=0.013', 
            'BRAT(1502)=0.987', 
            'BRAT(1555)=0.356', 
            'BRAT(1556)=0.644'),
        pythiaBottomoniumNRQCD = cms.vstring('MSUB(461) = 1', 
            'MSUB(462) = 1', 
            'MSUB(463) = 1', 
            'MSUB(464) = 1', 
            'MSUB(465) = 1', 
            'MSUB(466) = 1', 
            'MSUB(467) = 1', 
            'MSUB(468) = 1', 
            'MSUB(469) = 1', 
            'MSUB(470) = 1', 
            'MSUB(471) = 1', 
            'MSUB(472) = 1', 
            'MSUB(473) = 1', 
            'MSUB(474) = 1', 
            'MSUB(475) = 1', 
            'MSUB(476) = 1', 
            'MSUB(477) = 1', 
            'MSUB(478) = 1', 
            'MSUB(479) = 1'),
        pythiaWeakBosons = cms.vstring('MSUB(1)=1', 
            'MSUB(2)=1'),
        pythiaJets = cms.vstring('MSUB(11)=1', 
            'MSUB(12)=1', 
            'MSUB(13)=1', 
            'MSUB(28)=1', 
            'MSUB(53)=1', 
            'MSUB(68)=1'),
        pythiaZtoMuons = cms.vstring('MDME(174,1)=0', 
            'MDME(175,1)=0', 
            'MDME(176,1)=0', 
            'MDME(177,1)=0', 
            'MDME(178,1)=0', 
            'MDME(179,1)=0', 
            'MDME(182,1)=0', 
            'MDME(183,1)=0', 
            'MDME(184,1)=1', 
            'MDME(185,1)=0', 
            'MDME(186,1)=0', 
            'MDME(187,1)=0'),
        hydjetPythiaDefault = cms.vstring('MSEL=0   ! user processes', 
            'CKIN(3)=7.5', 
            'MSTP(81)=1'),
        ppJets = cms.vstring('MSEL=1   ! QCD hight pT processes'),
        pythiaHirootDefault = cms.vstring('MSEL=0', 
            'MSTU(21)=1', 
            'PARU(14)=1.', 
            'MSTP(81)=0', 
            'PMAS(5,1)=4.8', 
            'PMAS(6,1)=175.0', 
            'CKIN(3)=7.', 
            'MSTJ(22)=2', 
            'PARJ(71)=10.', 
            'PARP(67)=1.', 
            'PARP(82)=1.9', 
            'PARP(85)=0.33', 
            'PARP(86)=0.66', 
            'PARP(89)=1000.', 
            'PARP(91)=1.0', 
            'MSTJ(11)=3', 
            'MSTJ(22)=2'),
        pythiaJpsiToMuons = cms.vstring('BRAT(858) = 0 ', 
            'BRAT(859) = 1 ', 
            'BRAT(860) = 0 ', 
            'MDME(858,1) = 0 ', 
            'MDME(859,1) = 1 ', 
            'MDME(860,1) = 0 '),
        parameterSets = cms.vstring('pythiaUESettingsDrum', 
            'hydjetPythiaDefault', 
            'decayParameters',
            'pythiaJets', 
            'pythiaPromptPhotons', 
            'pythiaZjets', 
            'pythiaBottomoniumNRQCD', 
            'pythiaCharmoniumNRQCD', 
            'pythiaQuarkoniaSettings', 
            'pythiaWeakBosons')
    )
)





