import FWCore.ParameterSet.Config as cms

hltobject = cms.EDAnalyzer("TriggerObjectAnalyzer",
                           processName = cms.string("HLT"),
                           treeName = cms.string("JetTriggers"),
                           triggerNames = cms.vstring(
                               "HLT_HIAK4CaloJet100_v",
                               "HLT_HIDiPFJetAve35_HFJEC_v",
                               "HLT_HIAK4CaloJet120_v",
                               "HLT_HIAK4CaloJet40_v",
                               "HLT_HIAK4CaloJet60_v",
                               "HLT_HIAK4CaloJet80_v",
                               "HLT_HIDiPFJetAve25_HFJEC_v",
                               "HLT_HIDiPFJetAve15_HFJEC_v",
                               "HLT_HIAK4PFJet60_bTag_v",
                               "HLT_HIAK4PFJet80_bTag_v",
                               "HLT_HIAK4PFJet100_v",
                               "HLT_HIAK4PFJet120_v",
                               "HLT_HIAK4PFJet40_v",
                               "HLT_HIAK4PFJet60_v",
                               "HLT_HIAK4PFJet80_v",
                               "HLT_HIL1DoubleMu0_v",
                               "HLT_HIL1DoubleMu10_v",
                               "HLT_HIL2Mu15_v",
                               "HLT_HIL2Mu20_v",
                               "HLT_HIL2Mu3_NHitQ10_v",
                               "HLT_HIL2Mu5_NHitQ10_v",
                               "HLT_HIL3DoubleMu0_v",
                               "HLT_HIL3Mu15_v",
                               "HLT_HIL3Mu20_v",
                               "HLT_HIL3Mu3_NHitQ10_v",
                               "HLT_HIL3Mu5_NHitQ10_v",
                               "HLT_HISinglePhoton10_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton10_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton15_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton15_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton20_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton20_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton30_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton30_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton40_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton40_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton50_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton50_Eta3p1ForPPRef_v",
                               "HLT_HISinglePhoton60_Eta1p5ForPPRef_v",
                               "HLT_HISinglePhoton60_Eta3p1ForPPRef_v",
                               "HLT_HIPhoton20_HoverELoose_v",
                               "HLT_HIPhoton30_HoverELoose_v",
                               "HLT_HIPhoton40_HoverELoose_v",
                               "HLT_HIPhoton50_HoverELoose_v",
                               "HLT_HIPhoton60_HoverELoose_v",
                               "HLT_HIFullTracks_HighPt18_v",
                               "HLT_HIFullTracks_HighPt24_v",
                               "HLT_HIFullTracks_HighPt34_v",
                               "HLT_HIFullTracks_HighPt45_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt8_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt15_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt30_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt40_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt50_v",
                               "HLT_HIDmesonPPTrackingGlobal_Dpt60_v",
),
                           triggerResults = cms.InputTag("TriggerResults","","HLT"),
                           triggerEvent   = cms.InputTag("hltTriggerSummaryAOD","","HLT")
)
